// tts-voices.js
// 已移除所有 _tob 企业音色

window.XB_TTS_TTS2_VOICE_INFO = [
  { "value": "zh_female_vv_uranus_bigtts", "name": "Vivi 2.0", "scene": "通用场景" },
  { "value": "zh_female_xiaohe_uranus_bigtts", "name": "小何", "scene": "通用场景" },
  { "value": "zh_male_m191_uranus_bigtts", "name": "云舟", "scene": "通用场景" },
  { "value": "zh_male_taocheng_uranus_bigtts", "name": "小天", "scene": "通用场景" },
  { "value": "zh_male_dayi_saturn_bigtts", "name": "大壹", "scene": "视频配音" },
  { "value": "zh_female_mizai_saturn_bigtts", "name": "黑猫侦探社咪仔", "scene": "视频配音" },
  { "value": "zh_female_jitangnv_saturn_bigtts", "name": "鸡汤女", "scene": "视频配音" },
  { "value": "zh_female_meilinvyou_saturn_bigtts", "name": "魅力女友", "scene": "视频配音" },
  { "value": "zh_female_santongyongns_saturn_bigtts", "name": "流畅女声", "scene": "视频配音" },
  { "value": "zh_male_ruyayichen_saturn_bigtts", "name": "儒雅逸辰", "scene": "视频配音" },
  { "value": "zh_female_xueayi_saturn_bigtts", "name": "儿童绘本", "scene": "有声阅读" }
];

window.XB_TTS_VOICE_DATA = [
  // ========== TTS 2.0 ==========
  { "value": "zh_female_vv_uranus_bigtts", "name": "Vivi 2.0", "scene": "通用场景" },
  { "value": "zh_female_xiaohe_uranus_bigtts", "name": "小何", "scene": "通用场景" },
  { "value": "zh_male_m191_uranus_bigtts", "name": "云舟", "scene": "通用场景" },
  { "value": "zh_male_taocheng_uranus_bigtts", "name": "小天", "scene": "通用场景" },
  { "value": "zh_male_dayi_saturn_bigtts", "name": "大壹", "scene": "视频配音" },
  { "value": "zh_female_mizai_saturn_bigtts", "name": "黑猫侦探社咪仔", "scene": "视频配音" },
  { "value": "zh_female_jitangnv_saturn_bigtts", "name": "鸡汤女", "scene": "视频配音" },
  { "value": "zh_female_meilinvyou_saturn_bigtts", "name": "魅力女友", "scene": "视频配音" },
  { "value": "zh_female_santongyongns_saturn_bigtts", "name": "流畅女声", "scene": "视频配音" },
  { "value": "zh_male_ruyayichen_saturn_bigtts", "name": "儒雅逸辰", "scene": "视频配音" },
  { "value": "zh_female_xueayi_saturn_bigtts", "name": "儿童绘本", "scene": "有声阅读" },
  
  // ========== TTS 1.0 方言 ==========
  { "value": "zh_female_wanqudashu_moon_bigtts", "name": "湾区大叔", "scene": "趣味方言" },
  { "value": "zh_female_daimengchuanmei_moon_bigtts", "name": "呆萌川妹", "scene": "趣味方言" },
  { "value": "zh_male_guozhoudege_moon_bigtts", "name": "广州德哥", "scene": "趣味方言" },
  { "value": "zh_male_beijingxiaoye_moon_bigtts", "name": "北京小爷", "scene": "趣味方言" },
  { "value": "zh_male_haoyuxiaoge_moon_bigtts", "name": "浩宇小哥", "scene": "趣味方言" },
  { "value": "zh_male_guangxiyuanzhou_moon_bigtts", "name": "广西远舟", "scene": "趣味方言" },
  { "value": "zh_female_meituojieer_moon_bigtts", "name": "妹坨洁儿", "scene": "趣味方言" },
  { "value": "zh_male_yuzhouzixuan_moon_bigtts", "name": "豫州子轩", "scene": "趣味方言" },
  { "value": "zh_male_jingqiangkanye_moon_bigtts", "name": "京腔侃爷/Harmony", "scene": "趣味方言" },
  { "value": "zh_female_wanwanxiaohe_moon_bigtts", "name": "湾湾小何", "scene": "趣味方言" },
  
  // ========== TTS 1.0 通用 ==========
  { "value": "zh_male_shaonianzixin_moon_bigtts", "name": "少年梓辛/Brayan", "scene": "通用场景" },
  { "value": "zh_female_linjianvhai_moon_bigtts", "name": "邻家女孩", "scene": "通用场景" },
  { "value": "zh_male_yuanboxiaoshu_moon_bigtts", "name": "渊博小叔", "scene": "通用场景" },
  { "value": "zh_male_yangguangqingnian_moon_bigtts", "name": "阳光青年", "scene": "通用场景" },
  { "value": "zh_female_shuangkuaisisi_moon_bigtts", "name": "爽快思思/Skye", "scene": "通用场景" },
  { "value": "zh_male_wennuanahu_moon_bigtts", "name": "温暖阿虎/Alvin", "scene": "通用场景" },
  { "value": "zh_female_tianmeixiaoyuan_moon_bigtts", "name": "甜美小源", "scene": "通用场景" },
  { "value": "zh_female_qingchezizi_moon_bigtts", "name": "清澈梓梓", "scene": "通用场景" },
  { "value": "zh_male_jieshuoxiaoming_moon_bigtts", "name": "解说小明", "scene": "通用场景" },
  { "value": "zh_female_kailangjiejie_moon_bigtts", "name": "开朗姐姐", "scene": "通用场景" },
  { "value": "zh_male_linjiananhai_moon_bigtts", "name": "邻家男孩", "scene": "通用场景" },
  { "value": "zh_female_tianmeiyueyue_moon_bigtts", "name": "甜美悦悦", "scene": "通用场景" },
  { "value": "zh_female_xinlingjitang_moon_bigtts", "name": "心灵鸡汤", "scene": "通用场景" },
  { "value": "zh_female_qinqienvsheng_moon_bigtts", "name": "亲切女声", "scene": "通用场景" },
  { "value": "zh_female_cancan_mars_bigtts", "name": "灿灿", "scene": "通用场景" },
  { "value": "zh_female_zhixingnvsheng_mars_bigtts", "name": "知性女声", "scene": "通用场景" },
  { "value": "zh_female_qingxinnvsheng_mars_bigtts", "name": "清新女声", "scene": "通用场景" },
  { "value": "zh_female_linjia_mars_bigtts", "name": "邻家小妹", "scene": "通用场景" },
  { "value": "zh_male_qingshuangnanda_mars_bigtts", "name": "清爽男大", "scene": "通用场景" },
  { "value": "zh_female_tiexinnvsheng_mars_bigtts", "name": "贴心女声", "scene": "通用场景" },
  { "value": "zh_male_wenrouxiaoge_mars_bigtts", "name": "温柔小哥", "scene": "通用场景" },
  { "value": "zh_female_tianmeitaozi_mars_bigtts", "name": "甜美桃子", "scene": "通用场景" },
  { "value": "zh_female_kefunvsheng_mars_bigtts", "name": "暖阳女声", "scene": "通用场景" },
  { "value": "zh_male_qingyiyuxuan_mars_bigtts", "name": "阳光阿辰", "scene": "通用场景" },
  { "value": "zh_female_vv_mars_bigtts", "name": "Vivi", "scene": "通用场景" },
  { "value": "zh_male_ruyayichen_emo_v2_mars_bigtts", "name": "儒雅男友", "scene": "通用场景" },
  { "value": "zh_female_maomao_conversation_wvae_bigtts", "name": "文静毛毛", "scene": "通用场景" },
  { "value": "en_male_jason_conversation_wvae_bigtts", "name": "开朗学长", "scene": "通用场景" },
  
  // ========== TTS 1.0 角色扮演 ==========
  { "value": "zh_female_meilinvyou_moon_bigtts", "name": "魅力女友", "scene": "角色扮演" },
  { "value": "zh_male_shenyeboke_moon_bigtts", "name": "深夜播客", "scene": "角色扮演" },
  { "value": "zh_female_sajiaonvyou_moon_bigtts", "name": "柔美女友", "scene": "角色扮演" },
  { "value": "zh_female_yuanqinvyou_moon_bigtts", "name": "撒娇学妹", "scene": "角色扮演" },
  { "value": "zh_female_gaolengyujie_moon_bigtts", "name": "高冷御姐", "scene": "角色扮演" },
  { "value": "zh_male_aojiaobazong_moon_bigtts", "name": "傲娇霸总", "scene": "角色扮演" },
  { "value": "zh_female_wenrouxiaoya_moon_bigtts", "name": "温柔小雅", "scene": "角色扮演" },
  { "value": "zh_male_dongfanghaoran_moon_bigtts", "name": "东方浩然", "scene": "角色扮演" },
  { "value": "zh_male_tiancaitongsheng_mars_bigtts", "name": "天才童声", "scene": "角色扮演" },
  { "value": "zh_male_naiqimengwa_mars_bigtts", "name": "奶气萌娃", "scene": "角色扮演" },
  { "value": "zh_male_sunwukong_mars_bigtts", "name": "猴哥", "scene": "角色扮演" },
  { "value": "zh_male_xionger_mars_bigtts", "name": "熊二", "scene": "角色扮演" },
  { "value": "zh_female_peiqi_mars_bigtts", "name": "佩奇猪", "scene": "角色扮演" },
  { "value": "zh_female_popo_mars_bigtts", "name": "婆婆", "scene": "角色扮演" },
  { "value": "zh_female_wuzetian_mars_bigtts", "name": "武则天", "scene": "角色扮演" },
  { "value": "zh_female_shaoergushi_mars_bigtts", "name": "少儿故事", "scene": "角色扮演" },
  { "value": "zh_male_silang_mars_bigtts", "name": "四郎", "scene": "角色扮演" },
  { "value": "zh_female_gujie_mars_bigtts", "name": "顾姐", "scene": "角色扮演" },
  { "value": "zh_female_yingtaowanzi_mars_bigtts", "name": "樱桃丸子", "scene": "角色扮演" },
  { "value": "zh_female_qiaopinvsheng_mars_bigtts", "name": "俏皮女声", "scene": "角色扮演" },
  { "value": "zh_female_mengyatou_mars_bigtts", "name": "萌丫头", "scene": "角色扮演" },
  { "value": "zh_male_zhoujielun_emo_v2_mars_bigtts", "name": "双节棍小哥", "scene": "角色扮演" },
  { "value": "zh_female_jiaochuan_mars_bigtts", "name": "娇喘女声", "scene": "角色扮演" },
  { "value": "zh_male_livelybro_mars_bigtts", "name": "开朗弟弟", "scene": "角色扮演" },
  { "value": "zh_female_flattery_mars_bigtts", "name": "谄媚女声", "scene": "角色扮演" },
  
  // ========== TTS 1.0 播报解说 ==========
  { "value": "en_female_anna_mars_bigtts", "name": "Anna", "scene": "播报解说" },
  { "value": "zh_male_changtianyi_mars_bigtts", "name": "悬疑解说", "scene": "播报解说" },
  { "value": "zh_male_jieshuonansheng_mars_bigtts", "name": "磁性解说男声", "scene": "播报解说" },
  { "value": "zh_female_jitangmeimei_mars_bigtts", "name": "鸡汤妹妹", "scene": "播报解说" },
  { "value": "zh_male_chunhui_mars_bigtts", "name": "广告解说", "scene": "播报解说" },
  
  // ========== TTS 1.0 有声阅读 ==========
  { "value": "zh_male_ruyaqingnian_mars_bigtts", "name": "儒雅青年", "scene": "有声阅读" },
  { "value": "zh_male_baqiqingshu_mars_bigtts", "name": "霸气青叔", "scene": "有声阅读" },
  { "value": "zh_male_qingcang_mars_bigtts", "name": "擎苍", "scene": "有声阅读" },
  { "value": "zh_male_yangguangqingnian_mars_bigtts", "name": "活力小哥", "scene": "有声阅读" },
  { "value": "zh_female_gufengshaoyu_mars_bigtts", "name": "古风少御", "scene": "有声阅读" },
  { "value": "zh_female_wenroushunv_mars_bigtts", "name": "温柔淑女", "scene": "有声阅读" },
  { "value": "zh_male_fanjuanqingnian_mars_bigtts", "name": "反卷青年", "scene": "有声阅读" },
  
  // ========== TTS 1.0 视频配音 ==========
  { "value": "zh_male_dongmanhaimian_mars_bigtts", "name": "亮嗓萌仔", "scene": "视频配音" },
  { "value": "zh_male_lanxiaoyang_mars_bigtts", "name": "懒音绵宝", "scene": "视频配音" },
  
  // ========== TTS 1.0 教育场景 ==========
  { "value": "zh_female_yingyujiaoyu_mars_bigtts", "name": "Tina老师", "scene": "教育场景" },
  
  // ========== TTS 1.0 趣味口音 ==========
  { "value": "zh_male_hupunan_mars_bigtts", "name": "沪普男", "scene": "趣味口音" },
  { "value": "zh_male_lubanqihao_mars_bigtts", "name": "鲁班七号", "scene": "趣味口音" },
  { "value": "zh_female_yangmi_mars_bigtts", "name": "林潇", "scene": "趣味口音" },
  { "value": "zh_female_linzhiling_mars_bigtts", "name": "玲玲姐姐", "scene": "趣味口音" },
  { "value": "zh_female_jiyejizi2_mars_bigtts", "name": "春日部姐姐", "scene": "趣味口音" },
  { "value": "zh_male_tangseng_mars_bigtts", "name": "唐僧", "scene": "趣味口音" },
  { "value": "zh_male_zhuangzhou_mars_bigtts", "name": "庄周", "scene": "趣味口音" },
  { "value": "zh_male_zhubajie_mars_bigtts", "name": "猪八戒", "scene": "趣味口音" },
  { "value": "zh_female_ganmaodianyin_mars_bigtts", "name": "感冒电音姐姐", "scene": "趣味口音" },
  { "value": "zh_female_naying_mars_bigtts", "name": "直率英子", "scene": "趣味口音" },
  { "value": "zh_female_leidian_mars_bigtts", "name": "女雷神", "scene": "趣味口音" },
  { "value": "zh_female_yueyunv_mars_bigtts", "name": "粤语小溏", "scene": "趣味口音" },
  
  // ========== TTS 1.0 多情感 ==========
  { "value": "zh_male_beijingxiaoye_emo_v2_mars_bigtts", "name": "北京小爷（多情感）", "scene": "多情感" },
  { "value": "zh_female_roumeinvyou_emo_v2_mars_bigtts", "name": "柔美女友（多情感）", "scene": "多情感" },
  { "value": "zh_male_yangguangqingnian_emo_v2_mars_bigtts", "name": "阳光青年（多情感）", "scene": "多情感" },
  { "value": "zh_female_meilinvyou_emo_v2_mars_bigtts", "name": "魅力女友（多情感）", "scene": "多情感" },
  { "value": "zh_female_shuangkuaisisi_emo_v2_mars_bigtts", "name": "爽快思思（多情感）", "scene": "多情感" },
  { "value": "zh_male_junlangnanyou_emo_v2_mars_bigtts", "name": "俊朗男友（多情感）", "scene": "多情感" },
  { "value": "zh_male_yourougongzi_emo_v2_mars_bigtts", "name": "优柔公子（多情感）", "scene": "多情感" },
  { "value": "zh_female_linjuayi_emo_v2_mars_bigtts", "name": "邻居阿姨（多情感）", "scene": "多情感" },
  { "value": "zh_male_jingqiangkanye_emo_mars_bigtts", "name": "京腔侃爷（多情感）", "scene": "多情感" },
  { "value": "zh_male_guangzhoudege_emo_mars_bigtts", "name": "广州德哥（多情感）", "scene": "多情感" },
  { "value": "zh_male_aojiaobazong_emo_v2_mars_bigtts", "name": "傲娇霸总（多情感）", "scene": "多情感" },
  { "value": "zh_female_tianxinxiaomei_emo_v2_mars_bigtts", "name": "甜心小美（多情感）", "scene": "多情感" },
  { "value": "zh_female_gaolengyujie_emo_v2_mars_bigtts", "name": "高冷御姐（多情感）", "scene": "多情感" },
  { "value": "zh_male_lengkugege_emo_v2_mars_bigtts", "name": "冷酷哥哥（多情感）", "scene": "多情感" },
  { "value": "zh_male_shenyeboke_emo_v2_mars_bigtts", "name": "深夜播客（多情感）", "scene": "多情感" },
  
  // ========== TTS 1.0 多语种 ==========
  { "value": "multi_female_shuangkuaisisi_moon_bigtts", "name": "はるこ/Esmeralda", "scene": "多语种" },
  { "value": "multi_male_jingqiangkanye_moon_bigtts", "name": "かずね/Javier", "scene": "多语种" },
  { "value": "multi_female_gaolengyujie_moon_bigtts", "name": "あけみ", "scene": "多语种" },
  { "value": "multi_male_wanqudashu_moon_bigtts", "name": "ひろし/Roberto", "scene": "多语种" },
  { "value": "en_male_adam_mars_bigtts", "name": "Adam", "scene": "多语种" },
  { "value": "en_female_sarah_mars_bigtts", "name": "Sarah", "scene": "多语种" },
  { "value": "en_male_dryw_mars_bigtts", "name": "Dryw", "scene": "多语种" },
  { "value": "en_male_smith_mars_bigtts", "name": "Smith", "scene": "多语种" },
  { "value": "en_male_jackson_mars_bigtts", "name": "Jackson", "scene": "多语种" },
  { "value": "en_female_amanda_mars_bigtts", "name": "Amanda", "scene": "多语种" },
  { "value": "en_female_emily_mars_bigtts", "name": "Emily", "scene": "多语种" },
  { "value": "multi_male_xudong_conversation_wvae_bigtts", "name": "まさお/Daníel", "scene": "多语种" },
  { "value": "multi_female_sophie_conversation_wvae_bigtts", "name": "さとみ/Sofía", "scene": "多语种" },
  { "value": "zh_male_M100_conversation_wvae_bigtts", "name": "悠悠君子/Lucas", "scene": "多语种" },
  { "value": "zh_male_xudong_conversation_wvae_bigtts", "name": "快乐小东/Daniel", "scene": "多语种" },
  { "value": "zh_female_sophie_conversation_wvae_bigtts", "name": "魅力苏菲/Sophie", "scene": "多语种" },
  { "value": "multi_zh_male_youyoujunzi_moon_bigtts", "name": "ひかる（光）", "scene": "多语种" },
  { "value": "en_male_charlie_conversation_wvae_bigtts", "name": "Owen", "scene": "多语种" },
  { "value": "en_female_sarah_new_conversation_wvae_bigtts", "name": "Luna", "scene": "多语种" },
  { "value": "en_female_dacey_conversation_wvae_bigtts", "name": "Daisy", "scene": "多语种" },
  { "value": "multi_female_maomao_conversation_wvae_bigtts", "name": "つき/Diana", "scene": "多语种" },
  { "value": "multi_male_M100_conversation_wvae_bigtts", "name": "Lucía", "scene": "多语种" },
  { "value": "en_male_campaign_jamal_moon_bigtts", "name": "Energetic Male II", "scene": "多语种" },
  { "value": "en_male_chris_moon_bigtts", "name": "Gotham Hero", "scene": "多语种" },
  { "value": "en_female_daisy_moon_bigtts", "name": "Delicate Girl", "scene": "多语种" },
  { "value": "en_female_product_darcie_moon_bigtts", "name": "Flirty Female", "scene": "多语种" },
  { "value": "en_female_emotional_moon_bigtts", "name": "Peaceful Female", "scene": "多语种" },
  { "value": "en_male_bruce_moon_bigtts", "name": "Bruce", "scene": "多语种" },
  { "value": "en_male_dave_moon_bigtts", "name": "Dave", "scene": "多语种" },
  { "value": "en_male_hades_moon_bigtts", "name": "Hades", "scene": "多语种" },
  { "value": "en_male_michael_moon_bigtts", "name": "Michael", "scene": "多语种" },
  { "value": "en_female_onez_moon_bigtts", "name": "Onez", "scene": "多语种" },
  { "value": "en_female_nara_moon_bigtts", "name": "Nara", "scene": "多语种" },
  { "value": "en_female_lauren_moon_bigtts", "name": "Lauren", "scene": "多语种" },
  { "value": "en_female_candice_emo_v2_mars_bigtts", "name": "Candice", "scene": "多语种" },
  { "value": "en_male_corey_emo_v2_mars_bigtts", "name": "Corey", "scene": "多语种" },
  { "value": "en_male_glen_emo_v2_mars_bigtts", "name": "Glen", "scene": "多语种" },
  { "value": "en_female_nadia_tips_emo_v2_mars_bigtts", "name": "Nadia1", "scene": "多语种" },
  { "value": "en_female_nadia_poetry_emo_v2_mars_bigtts", "name": "Nadia2", "scene": "多语种" },
  { "value": "en_male_sylus_emo_v2_mars_bigtts", "name": "Sylus", "scene": "多语种" },
  { "value": "en_female_skye_emo_v2_mars_bigtts", "name": "Serena", "scene": "多语种" }
];
